name: Build firmware binaries
on: [push, pull_request]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Build binaries
        uses: Rockman18/ghactions-mplabx@master
        with:
          project: cutcutgo_bl.X
          configuration: cutcutgo-bl

      - name: Move binaries
        run: mkdir output && cp cutcutgo_bl.X/dist/cutcutgo-bl/production/cutcutgo-bl.X.production.hex output/cutcutgo_bootloader_for_maker1.hex

      - name: Upload firmware binaries
        uses: actions/upload-artifact@v3
        with:
          name: cutcutgo_bootloader_for_maker1.hex
          path: output/cutcutgo_bootloader_for_maker1.hex
          if-no-files-found: error

